// <auto-generated by="the Blazor I18n Text compiler" />
namespace Apoyo.Client.I18nText
{
    public partial class Text : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"About"</summary>
        public string Acerca;

        /// <summary>"My tasks"</summary>
        public string Actividades;

        /// <summary>"Add"</summary>
        public string Agregar;

        /// <summary>"Alumn"</summary>
        public string Alumno;

        /// <summary>"Schoolar help"</summary>
        public string Aplicacion;

        /// <summary>"Loading..."</summary>
        public string Cargando;

        /// <summary>"School cycle"</summary>
        public string ciclo;

        /// <summary>"Programaci�n WEB"</summary>
        public string Compania;

        /// <summary>"E-Mail"</summary>
        public string Correo;

        /// <summary>"Invalid Mail"</summary>
        public string correoInvalido;

        /// <summary>"Credits"</summary>
        public string Creditos;

        /// <summary>"Personal Information"</summary>
        public string Datos;

        /// <summary>"Availables"</summary>
        public string Disponible;

        /// <summary>"Teacher"</summary>
        public string Docente;

        /// <summary>"Error to authentificate"</summary>
        public string eAuthentic;

        /// <summary>"Error to create user"</summary>
        public string eCrearUsuario;

        /// <summary>"Edit"</summary>
        public string Editar;

        /// <summary>"Delete"</summary>
        public string Eliminar;

        /// <summary>"Error to send mail"</summary>
        public string eMail;

        /// <summary>"Try later"</summary>
        public string eMasTarde;

        /// <summary>"Send"</summary>
        public string Enviar;

        /// <summary>"Error to reset password"</summary>
        public string ePAsswordReset;

        /// <summary>"Please check the info"</summary>
        public string eRevisarInfo;

        /// <summary>"Error"</summary>
        public string Error;

        /// <summary>"First name"</summary>
        public string firstName;

        /// <summary>"Grups"</summary>
        public string Grupos;

        /// <summary>"Save"</summary>
        public string Guardar;

        /// <summary>"Hi"</summary>
        public string Hola;

        /// <summary>"Home"</summary>
        public string Inicio;

        /// <summary>"Send invitation"</summary>
        public string invitarUsuario;

        /// <summary>"Last name"</summary>
        public string lastNAme;

        /// <summary>"Alumn list"</summary>
        public string listaAlumnos;

        /// <summary>"Log In"</summary>
        public string LogIn;

        /// <summary>"Subjects"</summary>
        public string Materias;

        /// <summary>"Name"</summary>
        public string Nombre;

        /// <summary>"Unregister user"</summary>
        public string NoRegistrado;

        /// <summary>"Password"</summary>
        public string Password;

        /// <summary>"Password reset success"</summary>
        public string PasswordReset;

        /// <summary>"Phone number"</summary>
        public string Phone;

        /// <summary>"Privacy Policy"</summary>
        public string Politica;

        /// <summary>"Recovery password"</summary>
        public string Recovery;

        /// <summary>"Registrate"</summary>
        public string Registrate;

        /// <summary>"Logout"</summary>
        public string Salir;

        /// <summary>"Sure?"</summary>
        public string seguro;

        /// <summary>"Mail send "</summary>
        public string sendMail;

        /// <summary>"Services"</summary>
        public string Servicios;

        /// <summary>"No records found"</summary>
        public string SinRegistros;

        /// <summary>"Success"</summary>
        public string Success;

        /// <summary>"Terms"</summary>
        public string Terminos;

        /// <summary>"User Type"</summary>
        public string TipoUsuario;

        /// <summary>"User created success"</summary>
        public string UserC;

        /// <summary>"Username"</summary>
        public string Usuario;

        /// <summary>"Register user"</summary>
        public string usuarioRegistrado;
    }
}
